theme: jekyll-theme-minimal
title: Baggy Cat's Robo sapiens Project
description: Fat Cat the Robot AI Researcher
url: "http://kwpark-dev.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
