theme: jekyll-theme-minimal
title: Baggy Cat
avatar: /assets/images/blue_the_ascending.jpg
description: Fat Cat the Robot AI Researcher
url: "http://kwpark-dev.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
