theme: jekyll-theme-cayman
title: Robo sapiens Project
description: Fat Cat the Robot AI Researcher
url: "http://kwpark-dev.github.io"
author: Baggy Cat
avatar: /assets/images/blue_the_ascending.jpg

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag